### ISSUE TITLE
src/app/dynamic-component.directive.ts

### ISSUE THREAD

**Issue by shaan1974** [ezzabuzaid/dynamic-component-article#14]
Hello,

This piece of code help me a lot ( it's doing the same as <component> tag in Vue ).

Right now i'm using Angular 13, but import 'ComponentFactory' and 'ComponentFactoryResolver' are set as deprecated.

So is it possible to update this directive to avoid this deprecated stuff ?

Thanks a lot and by the wat great job with this one.

Shaan1974

**Comment by ezzabuzaid** [comment]
Hi @shaan1974! I'm glad you're finding it helpful!

I updated the directive to adapt to Angular's new changes. few notes
1. The new API for component inspection only available in Angular v14 which means you still have to work with the current state till you upgrade.
2. There is an issue with the component inspector APIs [PR](https://github.com/angular/angular/pull/49737/files) - [Issue](https://github.com/angular/angular/issues/49734)
3. I couldn't use the new Angular's `componentRef.setInput` as change detection might run twice given that API will do first then our directive will do second.

The updated directive: src/app/dynamic-component.directive.v13.ts

**Comment by shaan1974** [comment]
Thanks a lot.

Your directive save my live ;) In fact i'v create a form builder with several basic elements, but i could also add new elements. And your directive help me to do that. it's allow me to avoid switch cases.

I don't understand why they don't implement natively for Angular something like the tag "component" in Vue.

Again thanks

**Comment by ezzabuzaid** [comment]
@shaan1974 we do have, it is `ngComponentOutlet` directive, as of v16 it supports adding inputs only

**Comment by shaan1974** [comment]
I need to add custom input so your directive is perfect.
